-- This file is auto-generated by shipwright.nvim
local common_fg = "#9EA2BB"
local inactive_bg = "#202331"
local inactive_fg = "#F0F5C4"

return {
	normal = {
		a = { bg = "#494F6A", fg = common_fg, gui = "bold" },
		b = { bg = "#363A50", fg = common_fg },
		c = { bg = "#242737", fg = "#EBEFC0" },
	},

	insert = {
		a = { bg = "#304550", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#55369F", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#3D3F33", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#3A2120", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
