-- This file is auto-generated by shipwright.nvim
local common_fg = "#544D37"
local inactive_bg = "#E2D199"
local inactive_fg = "#758690"

return {
	normal = {
		a = { bg = "#B0A377", fg = common_fg, gui = "bold" },
		b = { bg = "#C4B685", fg = common_fg },
		c = { bg = "#D6C691", fg = "#4F5B62" },
	},

	insert = {
		a = { bg = "#A6BBCF", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#ECAFD5", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#C8D7DF", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#EAD5D5", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
