-- This file is auto-generated by shipwright.nvim
local common_fg = "#92AFC4"
local inactive_bg = "#2D3840"
local inactive_fg = "#EDE5D4"

return {
	normal = {
		a = { bg = "#526370", fg = common_fg, gui = "bold" },
		b = { bg = "#41505A", fg = common_fg },
		c = { bg = "#313D45", fg = "#E7DCC4" },
	},

	insert = {
		a = { bg = "#3F5F5B", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#934B71", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#59544A", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#5B3233", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
