-- This file is auto-generated by shipwright.nvim
local common_fg = "#A1B6C6"
local inactive_bg = "#3D464D"
local inactive_fg = "#EDE5D4"

return {
	normal = {
		a = { bg = "#5F6C77", fg = common_fg, gui = "bold" },
		b = { bg = "#505B64", fg = common_fg },
		c = { bg = "#3F484F", fg = "#E7DCC4" },
	},

	insert = {
		a = { bg = "#4A6F6A", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#A95782", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#686357", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#6E3E3F", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
