-- This file is auto-generated by shipwright.nvim
local common_fg = "#A8A8B2"
local inactive_bg = "#2F2F3B"
local inactive_fg = "#E9E3C5"

return {
	normal = {
		a = { bg = "#5B5A6B", fg = common_fg, gui = "bold" },
		b = { bg = "#484858", fg = common_fg },
		c = { bg = "#343440", fg = "#DDD8BB" },
	},

	insert = {
		a = { bg = "#3C5661", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#69508D", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#504E44", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#502D30", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
