-- This file is auto-generated by shipwright.nvim
local common_fg = "#7BA9C5"
local inactive_bg = "#18252D"
local inactive_fg = "#D1E0DA"

return {
	normal = {
		a = { bg = "#3B5362", fg = common_fg, gui = "bold" },
		b = { bg = "#2B3E49", fg = common_fg },
		c = { bg = "#1C2A32", fg = "#C6D5CF" },
	},

	insert = {
		a = { bg = "#343F6D", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#62415B", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#3A3E3D", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#3B2023", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
