-- This file is auto-generated by shipwright.nvim
local common_fg = "#4A4F4A"
local inactive_bg = "#D0DED2"
local inactive_fg = "#4B663C"

return {
	normal = {
		a = { bg = "#A3AEA4", fg = common_fg, gui = "bold" },
		b = { bg = "#B5C1B7", fg = common_fg },
		c = { bg = "#CAD8CC", fg = "#202E18" },
	},

	insert = {
		a = { bg = "#A6BBCF", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#DCB5D4", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#ADE48C", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#EAD5D7", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
