-- This file is auto-generated by shipwright.nvim
local common_fg = "#484D48"
local inactive_bg = "#CBD7CD"
local inactive_fg = "#4B663C"

return {
	normal = {
		a = { bg = "#9FA8A0", fg = common_fg, gui = "bold" },
		b = { bg = "#B1BBB2", fg = common_fg },
		c = { bg = "#C3CFC5", fg = "#202E18" },
	},

	insert = {
		a = { bg = "#9BB4C9", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#D8ABCE", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#A6DB86", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#E5CBCE", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
