-- This file is auto-generated by shipwright.nvim
local common_fg = "#A2AEC8"
local inactive_bg = "#313949"
local inactive_fg = "#F2F4F7"

return {
	normal = {
		a = { bg = "#57647D", fg = common_fg, gui = "bold" },
		b = { bg = "#465065", fg = common_fg },
		c = { bg = "#353E4F", fg = "#EBEEF3" },
	},

	insert = {
		a = { bg = "#426261", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#7B5C76", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#4D5867", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#5D3438", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
