-- This file is auto-generated by shipwright.nvim
local common_fg = "#ACB3C5"
local inactive_bg = "#404754"
local inactive_fg = "#F2F4F7"

return {
	normal = {
		a = { bg = "#646D81", fg = common_fg, gui = "bold" },
		b = { bg = "#545C6D", fg = common_fg },
		c = { bg = "#424957", fg = "#EBEEF3" },
	},

	insert = {
		a = { bg = "#4D7170", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#8D6987", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#5B6678", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#704044", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
