-- This file is auto-generated by shipwright.nvim
local common_fg = "#A4A1B7"
local inactive_bg = "#242232"
local inactive_fg = "#E9E0E0"

return {
	normal = {
		a = { bg = "#696485", fg = common_fg, gui = "bold" },
		b = { bg = "#45415D", fg = common_fg },
		c = { bg = "#312E43", fg = "#E1D4D4" },
	},

	insert = {
		a = { bg = "#30484C", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#673592", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#523A39", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#3D2229", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
