-- This file is auto-generated by shipwright.nvim
local common_fg = "#BDB4B5"
local inactive_bg = "#574A4D"
local inactive_fg = "#E5E5E5"

return {
	normal = {
		a = { bg = "#827073", fg = common_fg, gui = "bold" },
		b = { bg = "#6F5F62", fg = common_fg },
		c = { bg = "#5D4F51", fg = "#DDDDDD" },
	},

	insert = {
		a = { bg = "#577892", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#7A7BA7", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#6F6F6F", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#784A57", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
