-- This file is auto-generated by shipwright.nvim
local common_fg = "#4B4B4B"
local inactive_bg = "#D4D4D4"
local inactive_fg = "#818181"

return {
	normal = {
		a = { bg = "#A6A6A6", fg = common_fg, gui = "bold" },
		b = { bg = "#B9B9B9", fg = common_fg },
		c = { bg = "#CCCCCC", fg = "#555555" },
	},

	insert = {
		a = { bg = "#99B5C3", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#CBB1CA", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#CCCCCC", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#E5CBD1", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
