-- This file is auto-generated by shipwright.nvim
local common_fg = "#554B4D"
local inactive_bg = "#DCD9DA"
local inactive_fg = "#818181"

return {
	normal = {
		a = { bg = "#B2A9AA", fg = common_fg, gui = "bold" },
		b = { bg = "#C3BDBE", fg = common_fg },
		c = { bg = "#D7D3D4", fg = "#555555" },
	},

	insert = {
		a = { bg = "#A0BDCC", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#D1BAD0", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#D4D4D4", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#EAD5DA", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
