-- This file is auto-generated by shipwright.nvim
local common_fg = "#44464F"
local inactive_bg = "#B7B8C0"
local inactive_fg = "#5F6B9B"

return {
	normal = {
		a = { bg = "#8E909C", fg = common_fg, gui = "bold" },
		b = { bg = "#9EA0AB", fg = common_fg },
		c = { bg = "#ACADB6", fg = "#333A57" },
	},

	insert = {
		a = { bg = "#929EBC", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#ABA0C3", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#B2B8D3", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#DBB5BA", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
