-- This file is auto-generated by shipwright.nvim
local common_fg = "#44464F"
local inactive_bg = "#BFC1C7"
local inactive_fg = "#5F6B9B"

return {
	normal = {
		a = { bg = "#9698A3", fg = common_fg, gui = "bold" },
		b = { bg = "#A6A8B2", fg = common_fg },
		c = { bg = "#BABBC3", fg = "#333A57" },
	},

	insert = {
		a = { bg = "#929EBC", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#ABA0C3", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#B2B8D3", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#DBB5BA", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
