-- This file is auto-generated by shipwright.nvim
local common_fg = "#474B5A"
local inactive_bg = "#C4C6D0"
local inactive_fg = "#5F6B9B"

return {
	normal = {
		a = { bg = "#979BAC", fg = common_fg, gui = "bold" },
		b = { bg = "#AAADBC", fg = common_fg },
		c = { bg = "#BBBEC9", fg = "#333A57" },
	},

	insert = {
		a = { bg = "#A4AEC7", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#BAB2CE", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#C4C8DD", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#E4C8CC", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
