-- This file is auto-generated by shipwright.nvim
local common_fg = "#9FA1BB"
local inactive_bg = "#1F2031"
local inactive_fg = "#D2D9F8"

return {
	normal = {
		a = { bg = "#5D6088", fg = common_fg, gui = "bold" },
		b = { bg = "#3B3E5A", fg = common_fg },
		c = { bg = "#292B3F", fg = "#C0CAF5" },
	},

	insert = {
		a = { bg = "#313F61", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#641DAE", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#27396A", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#381E22", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
