-- This file is auto-generated by shipwright.nvim
local common_fg = "#9FA1BB"
local inactive_bg = "#1F2031"
local inactive_fg = "#D2D9F8"

return {
	normal = {
		a = { bg = "#4A4E6F", fg = common_fg, gui = "bold" },
		b = { bg = "#353751", fg = common_fg },
		c = { bg = "#232437", fg = "#C0CAF5" },
	},

	insert = {
		a = { bg = "#313F61", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#641DAE", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#27396A", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#381E22", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
