-- This file is auto-generated by shipwright.nvim
local common_fg = "#A5AAC5"
local inactive_bg = "#2F334B"
local inactive_fg = "#D2D9F8"

return {
	normal = {
		a = { bg = "#575F85", fg = common_fg, gui = "bold" },
		b = { bg = "#444A69", fg = common_fg },
		c = { bg = "#333851", fg = "#C0CAF5" },
	},

	insert = {
		a = { bg = "#445682", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#8429E1", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#375090", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#553137", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
