-- This file is auto-generated by shipwright.nvim
local common_fg = "#4E4E42"
local inactive_bg = "#CECEB1"
local inactive_fg = "#686868"

return {
	normal = {
		a = { bg = "#A2A28B", fg = common_fg, gui = "bold" },
		b = { bg = "#B5B59B", fg = common_fg },
		c = { bg = "#C3C3A7", fg = "#353535" },
	},

	insert = {
		a = { bg = "#9EB6CB", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#D9AFD0", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#CFCFCF", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#E7CFD1", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
