-- This file is auto-generated by shipwright.nvim
local common_fg = "#4E4E42"
local inactive_bg = "#D9D9BB"
local inactive_fg = "#686868"

return {
	normal = {
		a = { bg = "#AAAA92", fg = common_fg, gui = "bold" },
		b = { bg = "#BDBDA2", fg = common_fg },
		c = { bg = "#D1D1B3", fg = "#353535" },
	},

	insert = {
		a = { bg = "#9EB6CB", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#D9AFD0", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#CFCFCF", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#E7CFD1", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
