-- This file is auto-generated by shipwright.nvim
local common_fg = "#5C504A"
local inactive_bg = "#EAE4E1"
local inactive_fg = "#596A76"

return {
	normal = {
		a = { bg = "#C5AFA4", fg = common_fg, gui = "bold" },
		b = { bg = "#D4C7C0", fg = common_fg },
		c = { bg = "#E3DBD7", fg = "#2C363C" },
	},

	insert = {
		a = { bg = "#B4C6D6", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#E2C3DB", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#D6E1E9", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#F0E2E4", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
