-- This file is auto-generated by shipwright.nvim
local common_fg = "#B39C90"
local inactive_bg = "#241E1B"
local inactive_fg = "#CAD0D4"

return {
	normal = {
		a = { bg = "#574B45", fg = common_fg, gui = "bold" },
		b = { bg = "#413732", fg = common_fg },
		c = { bg = "#29221F", fg = "#B4BDC3" },
	},

	insert = {
		a = { bg = "#2D404E", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#5C3D56", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#37393B", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#361C1F", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
