-- This file is auto-generated by shipwright.nvim
local common_fg = "#B6B6B6"
local inactive_bg = "#525252"
local inactive_fg = "#F5EDE0"

return {
	normal = {
		a = { bg = "#868686", fg = common_fg, gui = "bold" },
		b = { bg = "#6A6A6A", fg = common_fg },
		c = { bg = "#5C5C5C", fg = "#F0E4CF" },
	},

	insert = {
		a = { bg = "#53738B", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#9C6992", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#746956", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#764544", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
