-- This file is auto-generated by shipwright.nvim
local common_fg = "#B9B9B9"
local inactive_bg = "#505050"
local inactive_fg = "#F5EDE0"

return {
	normal = {
		a = { bg = "#747474", fg = common_fg, gui = "bold" },
		b = { bg = "#636363", fg = common_fg },
		c = { bg = "#525252", fg = "#F0E4CF" },
	},

	insert = {
		a = { bg = "#597B94", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#A5709B", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#7C715C", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#804B4A", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
