-- This file is auto-generated by shipwright.nvim
local common_fg = "#B1A39C"
local inactive_bg = "#2D2927"
local inactive_fg = "#CAD0D4"

return {
	normal = {
		a = { bg = "#5E5652", fg = common_fg, gui = "bold" },
		b = { bg = "#47413E", fg = common_fg },
		c = { bg = "#342F2D", fg = "#B4BDC3" },
	},

	insert = {
		a = { bg = "#374E5F", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#6E4966", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#444749", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#47272B", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
