-- This file is auto-generated by shipwright.nvim
local common_fg = "#505050"
local inactive_bg = "#DDDDDD"
local inactive_fg = "#686868"

return {
	normal = {
		a = { bg = "#AEAEAE", fg = common_fg, gui = "bold" },
		b = { bg = "#C1C1C1", fg = common_fg },
		c = { bg = "#D7D7D7", fg = "#353535" },
	},

	insert = {
		a = { bg = "#A9BED1", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#DEB9D6", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#D7D7D7", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#EBD8DA", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
