-- This file is auto-generated by shipwright.nvim
local common_fg = "#A3A3A3"
local inactive_bg = "#242424"
local inactive_fg = "#CFCFCF"

return {
	normal = {
		a = { bg = "#686868", fg = common_fg, gui = "bold" },
		b = { bg = "#444444", fg = common_fg },
		c = { bg = "#303030", fg = "#BBBBBB" },
	},

	insert = {
		a = { bg = "#324757", fg = common_fg, gui = "bold" },
	},

	command = {
		a = { bg = "#65435E", fg = common_fg, gui = "bold" },
	},

	visual = {
		a = { bg = "#404040", fg = common_fg, gui = "bold" },
	},

	replace = {
		a = { bg = "#3E2225", fg = common_fg, gui = "bold" },
	},

	inactive = {
		a = { bg = inactive_bg, fg = inactive_fg, gui = "bold" },
		b = { bg = inactive_bg, fg = inactive_fg },
		c = { bg = inactive_bg, fg = inactive_fg },
	},
}
