local function to_term_colors(colorscheme)
	return {
		string.format("vim.g.terminal_color_0 = '%s'", term.black),
		string.format("vim.g.terminal_color_1 = '%s'", term.red),
		string.format("vim.g.terminal_color_2 = '%s'", term.green),
		string.format("vim.g.terminal_color_3 = '%s'", term.yellow),
		string.format("vim.g.terminal_color_4 = '%s'", term.blue),
		string.format("vim.g.terminal_color_5 = '%s'", term.magenta),
		string.format("vim.g.terminal_color_6 = '%s'", term.cyan),
		string.format("vim.g.terminal_color_7 = '%s'", term.white),
		string.format("vim.g.terminal_color_8 = '%s'", term.bright_black),
		string.format("vim.g.terminal_color_9 = '%s'", term.bright_red),
		string.format("vim.g.terminal_color_10 = '%s'", term.bright_green),
		string.format("vim.g.terminal_color_11 = '%s'", term.bright_yellow),
		string.format("vim.g.terminal_color_12 = '%s'", term.bright_blue),
		string.format("vim.g.terminal_color_13 = '%s'", term.bright_magenta),
		string.format("vim.g.terminal_color_14 = '%s'", term.bright_cyan),
		string.format("vim.g.terminal_color_15 = '%s'", term.bright_white),
	}
end

local function left_pad(lines, length)
	local padded_lines = {}
	for _, line in ipairs(lines) do
		line = table.insert(padded_lines, string.rep("	", length) .. line)
	end
	return padded_lines
end

local lushwright = require "shipwright.transform.lush"

---@diagnostic disable: undefined-global
-- selene: allow(undefined_variable)
run(
	specs,
	lushwright.to_lua,
	{ prepend, [[-- This codeblock is auto-generated by shipwright.nvim]] },
	{ left_pad, 1 },
	{
		patchwrite,
		string.format("lua/%s/prebuilt.lua", specs_name),
		string.format([[-- %s start]], background),
		string.format([[-- %s end]], background),
	}
)

run(
	specs,
	to_term_colors,
	{ prepend, [[-- This codeblock is auto-generated by shipwright.nvim]] },
	{ left_pad, 1 },
	{
		patchwrite,
		string.format("lua/%s/prebuilt.lua", specs_name),
		string.format([[-- %s term start]], background),
		string.format([[-- %s term end]], background),
	}
)
