---@diagnostic disable: undefined-global
-- selene: allow(undefined_variable)
run(
	{ specs, p, term },
	transform.colorscheme_to_term_colors,
	function(colors)
		return vim.tbl_extend("keep", colors, {
			cursor_border = specs.Cursor.fg,
		})
	end,
	contrib.wezterm,
	{ prepend, "# This file is auto-generated by shipwright.nvim" },
	{ overwrite, string.format("extras/wezterm/%s.toml", name:sub(1, 1):upper() .. name:sub(2)) }
)
-- selene: deny(undefined_variable)
---@diagnostic enable: undefined-global
