local template = [[{
                    "background": "$bg",
                    "black": "$black",
                    "blue": "$blue",
                    "brightBlack": "$bright_blank",
                    "brightBlue": "$bright_blue",
                    "brightCyan": "$bright_cyan",
                    "brightGreen": "$bright_green",
                    "brightPurple": "$bright_purple",
                    "brightRed": "$bright_red",
                    "brightWhite": "$bright_white",
                    "brightYellow": "$bright_yellow",
                    "cursorColor": "$cursor_fg",
                    "cyan": "$cyan",
                    "foreground": "$fg",
                    "green": "$green",
                    "name": "zenbonse",
                    "purple": "$purple",
                    "red": "$red",
                    "selectionBackground": "$selection_bg",
                    "white": "$white",
                    "yellow": "$yellow"
                    }
]]

local helpers = require "shipwright.transform.helpers"

---@diagnostic disable: undefined-global
-- selene: allow(undefined_variable)
run(
	{ specs, p, term },
	transform.colorscheme_to_term_colors,
	function(colors)
		local text = helpers.apply_template(template, colors)
		return { text }
	end,
	{ prepend, "# This file is auto-generated by shipwright.nvim" },
	{ overwrite, string.format("extras/windowsTerminal/%s.json", name) }
)
-- selene: deny(undefined_variable)
---@diagnostic enable: undefined-global
